"""Generate a runnable dbt project from a Portiere mapping.

Mirrors ``ETLRunner._process_table`` (select → rename → concept-lookup join) as
dbt SQL models, so the transform runs on any dbt adapter — no Portiere runtime,
no vendor lock-in, consistent with Portiere's standalone-artifact philosophy.

    from portiere.integrations.dbt import build_dbt_project
    build_dbt_project(schema_mapping, concept_mapping, "dbt_omop/")

Pure text generation — no dbt dependency required to produce the project.
"""

from __future__ import annotations

import csv
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

from portiere.standards import STANDARDS_DIR

if TYPE_CHECKING:
    from portiere.models.concept_mapping import ConceptMapping
    from portiere.models.schema_mapping import SchemaMapping


def _required_fields(standard: str) -> dict[str, set[str]]:
    """Return {entity: {required field names}} from the standard YAML."""
    path = STANDARDS_DIR / f"{standard}.yaml"
    if not path.exists():
        return {}
    std = yaml.safe_load(path.read_text())
    out: dict[str, set[str]] = {}
    for entity, ent in (std.get("entities") or {}).items():
        req = {f for f, meta in (ent.get("fields") or {}).items() if (meta or {}).get("required")}
        out[entity] = req
    return out


def _model_sql(
    target_table: str,
    source_table: str,
    renames: list[tuple[str, str]],
    unmapped: list[str],
    concept_cols: dict[str, str],
    source_schema: str,
    standard: str,
) -> str:
    """Render one models/<table>.sql."""
    lines = [
        f"-- Generated by Portiere — target: {target_table} ({standard})",
        "-- Do not edit by hand; regenerate with `portiere dbt`.",
        "",
        "with source as (",
        f"    select * from {{{{ source('{source_schema}', '{source_table}') }}}}",
        "),",
        "",
        "renamed as (",
        "    select",
    ]
    select_lines = [f"        {src} as {tgt}" for src, tgt in renames]
    for col in unmapped:
        select_lines.append(f"        -- UNMAPPED source column (needs review): {col}")
    # join select lines with commas, but comment lines don't take a trailing comma
    rendered = []
    real = [ln for ln in select_lines if "-- UNMAPPED" not in ln]
    for i, ln in enumerate(select_lines):
        if "-- UNMAPPED" in ln:
            rendered.append(ln)
        else:
            is_last_real = ln == real[-1]
            rendered.append(ln + ("" if is_last_real else ","))
    lines.extend(rendered)
    lines.extend(["    from source", ")"])

    if not concept_cols:
        lines.append("")
        lines.append("select * from renamed")
        return "\n".join(lines) + "\n"

    # Concept-lookup joins: one per mapped column, producing <col>_concept_id.
    lines[-1] = "),"
    lines.append("")
    lines.append("mapped as (")
    lines.append("    select")
    lines.append("        renamed.*,")
    join_selects = []
    join_clauses = []
    for idx, (col, vocab) in enumerate(concept_cols.items()):
        alias = f"scm_{idx}"
        join_selects.append(f"        coalesce({alias}.target_concept_id, 0) as {col}_concept_id")
        join_clauses.append(
            f"    left join {{{{ ref('source_to_concept_map') }}}} {alias}\n"
            f"        on {alias}.source_code = renamed.{col}\n"
            f"       and {alias}.source_vocabulary_id = '{vocab}'"
        )
    lines.append(",\n".join(join_selects))
    lines.append("    from renamed")
    lines.extend(join_clauses)
    lines.append(")")
    lines.append("")
    lines.append("select * from mapped")
    return "\n".join(lines) + "\n"


def build_dbt_project(
    schema_mapping: SchemaMapping,
    concept_mapping: ConceptMapping | None,
    out_dir: str | Path,
    *,
    project_name: str = "portiere_dbt",
    source_schema: str = "raw",
    standard: str = "omop_cdm_v5.4",
) -> Path:
    """Generate a dbt project and return its root path."""
    out = Path(out_dir)
    (out / "models").mkdir(parents=True, exist_ok=True)

    required = _required_fields(standard)

    # Concept mappings: group by source column → (vocab, seed rows).
    concept_by_col: dict[str, str] = {}
    seed_rows: list[dict[str, Any]] = []
    if concept_mapping is not None:
        for it in concept_mapping.items:
            col = it.source_column or ""
            vocab = it.target_vocabulary_id or col
            if col:
                concept_by_col[col] = col  # join key is the source column name
            seed_rows.append(
                {
                    "source_code": it.source_code,
                    "source_vocabulary_id": col,
                    "target_concept_id": it.target_concept_id or 0,
                    "target_concept_name": it.target_concept_name or "",
                    "confidence": round(float(it.confidence), 3),
                    "method": it.method.value if hasattr(it.method, "value") else str(it.method),
                }
            )

    # Group schema items by target table.
    by_table: dict[str, list] = defaultdict(list)
    for item in schema_mapping.items:
        table = item.effective_target_table
        if table:
            by_table[table].append(item)

    models_meta: list[dict] = []
    for table, items in sorted(by_table.items()):
        source_tables = {i.source_table for i in items if i.source_table}
        source_table = sorted(source_tables)[0] if source_tables else "source"

        renames: list[tuple[str, str]] = []
        unmapped: list[str] = []
        seen_targets: set[str] = set()
        concept_cols: dict[str, str] = {}
        for i in items:
            tgt = i.effective_target_column
            if not tgt:
                unmapped.append(i.source_column)
                continue
            if tgt in seen_targets:
                continue
            seen_targets.add(tgt)
            renames.append((i.source_column, tgt))
            if i.source_column in concept_by_col:
                concept_cols[tgt] = concept_by_col[i.source_column]

        sql = _model_sql(
            table, source_table, renames, unmapped, concept_cols, source_schema, standard
        )
        (out / "models" / f"{table}.sql").write_text(sql)

        # schema.yml columns + not_null tests on required standard fields.
        req = required.get(table, set())
        columns_meta = []
        for _src, tgt in renames:
            entry: dict[str, Any] = {"name": tgt}
            if tgt in req:
                entry["tests"] = ["not_null"]
            columns_meta.append(entry)
        for col in concept_cols:
            columns_meta.append({"name": f"{col}_concept_id"})
        models_meta.append(
            {
                "name": table,
                "description": f"Portiere-mapped {table} ({standard}).",
                "columns": columns_meta,
            }
        )

    (out / "models" / "schema.yml").write_text(
        yaml.safe_dump({"version": 2, "models": models_meta}, sort_keys=False)
    )

    # Seed
    if seed_rows:
        (out / "seeds").mkdir(exist_ok=True)
        with (out / "seeds" / "source_to_concept_map.csv").open(
            "w", newline="", encoding="utf-8"
        ) as f:
            writer = csv.DictWriter(f, fieldnames=list(seed_rows[0]))
            writer.writeheader()
            writer.writerows(seed_rows)

    # dbt_project.yml
    project_cfg = {
        "name": project_name,
        "version": "1.0.0",
        "config-version": 2,
        "profile": project_name,
        "model-paths": ["models"],
        "seed-paths": ["seeds"],
        "models": {project_name: {"+materialized": "table"}},
    }
    (out / "dbt_project.yml").write_text(yaml.safe_dump(project_cfg, sort_keys=False))

    # README provenance
    from portiere import __version__

    stamp = datetime.now(tz=timezone.utc).isoformat(timespec="seconds")
    (out / "README.md").write_text(
        f"# {project_name}\n\n"
        f"Generated by Portiere v{__version__} at {stamp} (UTC) — target standard "
        f"`{standard}`.\n\n"
        "This is a **generated** dbt project (select → rename → concept-lookup "
        "join, one model per target table). Edit the Portiere mapping and "
        "regenerate with `portiere dbt`; do not hand-edit the models.\n\n"
        "## Run\n\n"
        "```bash\n"
        "dbt seed     # load source_to_concept_map\n"
        "dbt run      # build the target tables\n"
        "dbt test     # required-field + relationship checks\n"
        "```\n\n"
        f"Configure a `{source_schema}` source and a `{project_name}` profile in "
        "your dbt setup pointing at your warehouse.\n"
    )
    return out


__all__ = ["build_dbt_project"]
