"""Shared openpyxl styling for the Portiere deliverable workbooks.

Import-guarded: openpyxl ships in the optional ``xlsx`` extra
(``pip install "portiere-health[xlsx]"``).
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def require_openpyxl():
    """Import openpyxl or raise a helpful error."""
    try:
        import openpyxl

        return openpyxl
    except ImportError as exc:
        raise ImportError(
            "Excel workbook export requires openpyxl. "
            'Install it with: pip install "portiere-health[xlsx]"'
        ) from exc


# House palette (hex, no leading #, openpyxl ARGB style)
HEADER_FILL = "1F6F6B"  # deep teal
HEADER_FONT = "FFFFFF"
TITLE_FONT = "1F6F6B"
STATUS_COLORS = {
    "approved": "C6EFCE",  # green
    "auto": "C6EFCE",
    "overridden": "BDD7EE",  # blue
    "needs_review": "FFEB9C",  # amber
    "review": "FFEB9C",
    "rejected": "FFC7CE",  # red
    "manual": "FFC7CE",
    "unmapped": "F2F2F2",  # grey
    "UNMAPPED": "F2F2F2",
}


def style_header_row(ws, n_cols: int, row: int = 1) -> None:
    """Bold white-on-teal header, frozen panes below, autofilter."""
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    fill = PatternFill("solid", fgColor=HEADER_FILL)
    font = Font(bold=True, color=HEADER_FONT)
    for col in range(1, n_cols + 1):
        cell = ws.cell(row=row, column=col)
        cell.fill = fill
        cell.font = font
        cell.alignment = Alignment(vertical="center", wrap_text=True)
    ws.freeze_panes = ws.cell(row=row + 1, column=1)
    ws.auto_filter.ref = f"A{row}:{get_column_letter(n_cols)}{max(ws.max_row, row)}"


def autosize_columns(ws, max_width: int = 48, sample_rows: int = 200) -> None:
    """Approximate column autosize from cell content lengths."""
    from openpyxl.utils import get_column_letter

    widths: dict[int, int] = {}
    for r, row in enumerate(ws.iter_rows(values_only=True)):
        if r >= sample_rows:
            break
        for i, v in enumerate(row, start=1):
            if v is None:
                continue
            widths[i] = min(max(widths.get(i, 8), len(str(v)) + 2), max_width)
    for i, w in widths.items():
        ws.column_dimensions[get_column_letter(i)].width = w


def add_percent_databar(ws, col_letter: str, first_row: int, last_row: int) -> None:
    """Green data bar over a 0-100 percentage column."""
    from openpyxl.formatting.rule import DataBarRule

    if last_row < first_row:
        return
    rule = DataBarRule(
        start_type="num", start_value=0, end_type="num", end_value=100, color="2E7D32"
    )
    ws.conditional_formatting.add(f"{col_letter}{first_row}:{col_letter}{last_row}", rule)


def fill_status_cell(cell, status: Any) -> None:
    """Color a status cell per the house status palette."""
    from openpyxl.styles import PatternFill

    color = STATUS_COLORS.get(str(status))
    if color:
        cell.fill = PatternFill("solid", fgColor=color)


def safe_sheet_name(name: str, used: set[str]) -> str:
    """Excel-legal (≤31 chars, unique, no forbidden chars) sheet name."""
    cleaned = "".join("_" if ch in r"[]:*?/\\" else ch for ch in name)[:31]
    candidate = cleaned or "sheet"
    n = 1
    while candidate in used:
        suffix = f"~{n}"
        candidate = cleaned[: 31 - len(suffix)] + suffix
        n += 1
    used.add(candidate)
    return candidate


def add_toc(wb, entries: list[tuple[str, str]]) -> None:
    """Prepend a hyperlinked table-of-contents sheet.

    Args:
        wb: Workbook.
        entries: (label, sheet_name) pairs.
    """
    from openpyxl.styles import Font

    ws = wb.create_sheet("TOC", 0)
    ws["A1"] = "Contents"
    ws["A1"].font = Font(bold=True, size=14, color=TITLE_FONT)
    for i, (label, sheet) in enumerate(entries, start=3):
        cell = ws.cell(row=i, column=1, value=label)
        cell.hyperlink = f"#'{sheet}'!A1"
        cell.font = Font(color="0563C1", underline="single")
    autosize_columns(ws)


def provenance_lines(extra: dict[str, Any] | None = None) -> list[str]:
    """Standard generated-by block for readme/provenance sheets."""
    from portiere import __version__

    lines = [
        f"Generated by Portiere v{__version__}",
        f"Generated at (UTC): {datetime.now(tz=timezone.utc).isoformat(timespec='seconds')}",
    ]
    for k, v in (extra or {}).items():
        lines.append(f"{k}: {v}")
    return lines
